### ISSUE TITLE
PDF Download is from 2019

### ISSUE THREAD

**Issue by misilot** [saa-ts-dacs/saa-ts-dacs.github.io#17]
Hello, the PDF version is from 2019. Can the 2022 version be uploaded, and linked?

**Comment by kbogan** [comment]
Thanks for pointing this out. The SAA Publications committee determines how frequently the PDF is published (it replaces the old printed manual). That committee is separate from the TS-DACS committee which manages the Github site. Please let me know if that doesn't make sense or if you have further questions.
